// initial state
const state = {
  // 订单ID
  id: -1,
  // 订单编号
  num: '',
  // 就诊卡ID
  cardId: -1,
  // 就诊卡号
  cardNum: '',
  // 就诊卡姓名
  cardName: '',
  // 就诊卡类型
  cardType: '',
  // 病人编号
  patientId: '',
  // 职业
  occupation: '',
  // 民族
  nation: '',
  // 婚姻状况
  maritalStatus: '',
  // 出生地
  birthPlace: '',
  // 国籍
  citizenship: '',
  // 现住址地区编码
  mailingAddrAc: '',
  // 现住址
  mailingAddress: '',
  // 现住址门牌号码
  mailingAddrSn: '',
  // 现住址邮编
  zipCode: '',
  // 家庭电话
  phoneNumberHome: '',
  // 户口地址地区编码
  regResidenceAc: '',
  // 户口地址
  regResidence: '',
  // 户口地址门牌号码
  regResidenceSn: '',
  // 户口地址邮编
  regResidenceZipCode: '',
  // 工作单位名称
  unitName: '',
  // 工作单位地址地区编码
  unitAddrAc: '',
  // 工作单位地址
  unitAddress: '',
  // 工作单位地址门牌号码
  unitAddrSn: '',
  // 工作单位邮编
  unitZipCode: '',
  // 单位电话号码
  phoneNumberBusiness: '',
  // 联系人姓名
  nextOfKin: '',
  // 与联系人关系
  relationship: '',
  // 联系人地址
  nextOfKinAddr: '',
  // 联系人邮政编码
  nextOfKinZipCode: '',
  // 联系人电话号码
  nextOfKinPhone: '',
  // 籍贯
  nativePlace: ''
}
export default {
  state
}
